New features and streamlined per issue req 006 implemented

diff --git a/nospot b/nospot
--- a/nospot
+++ b/nospot
@@ -2,11 +2,14 @@
 
 # vim: set fileencoding=utf-8:
 # BSD 3-Clause License -- see LICENSE for details.
+# https://github.com/pr3d4t0r/SSScoring/blob/master/LICENSE
+#
 # https://github.com/pr3d4t0r/SSScoring for full project.
 
 
 # *** constants ***
 
+FLYSIGHT_SIG_FILE="CONFIG.TXT"
 MOUNT_POINT="/Volumes"
 OS="Darwin"
 
@@ -20,20 +23,60 @@ function die {
 
 
 function assertMacOS {
-    [[ $(uname) == "$OS" ]] || die "this tool only works on MacOS" 1
+    [[ $(uname) == "$OS" ]] || die "this tool is intended for MacOS/Spotlight" 1
 } # assertMacOS
 
 
-function canonicalPathFor {
-    [[ -z "$1" ]] && die "Provide a path to concatenate to $MOUNT_POINT" 3
-    echo "$MOUNT_POINT/$1"
-} # canonicalPathFor
+function resolveFlySightMount {
+    local flagFile
+    local mountPoint
+    local mountPoints=("$MOUNT_POINT"/*)
+    local result=""
+
+    for mountPoint in "${mountPoints[@]}"
+    do
+        flagFile="$mountPoint/$FLYSIGHT_SIG_FILE"
+
+        if [[ -e "$flagFile" ]]
+        then
+            result="$mountPoint"
+            break
+        fi
+    done
+
+    echo "$result"
+} # resolveFlySightMount
 
 
 function assertFlySightDirExists {
-    local directory=$(canonicalPathFor "$1")
+    local directory="$1"
 
-    [[ -d "$directory" ]] || die "$directory does not exist; try again" 2
+    [[ -n "$directory" ]] || die "no valid FlySight mount or directory found" 2
+    [[ -d "$directory" ]] || die "$directory does not exist; try again" 3
+}
+
+
+function notifyUserWorkWith {
+    printf "\nFlySight - disabling Spotlight scans in FlySight mount %s\n" "$1"
+    printf "This operation may take a severa minutes\n\n"
+} # notifyUserWorkWith
+
+
+function disableSpotlightIn {
+    local workDir="$1"
+
+    # Via FlySight / Michael Cooper recommendation:
+    # https://apple.stackexchange.com/a/7135
+
+    mdutil -i off "$workDir" || die "mdutil failed, ABEND" 4
+
+    pushd "$workDir" > /dev/null
+    rm -rf .fseventsd .Spotlight-V* .Trashes ._.Trashes
+    mkdir .fseventsd
+    touch .fseventsd/no_log .metadata_never_index .Trashes
+    popd > /dev/null
+
+    printf "Spotlight disabled for $workDir\n\n"
 }
 
 
@@ -42,32 +85,10 @@ function assertFlySightDirExists {
 set -e
 
 assertMacOS
-
-ls -Alrt "$MOUNT_POINT"
-
-read -p "Which directory? " dirFlySight
-
-assertFlySightDirExists "$dirFlySight"
-
-workDirectory=$(canonicalPathFor "$dirFlySight")
-
-printf "\nDisabling Spotlight scans on FlySight directory %s\n" "$workDirectory"
-echo "This operation may take a while"
-echo ""
-
-
-# Via FlySight / Michael Cooper recommendation:
-# https://apple.stackexchange.com/a/7135
-
-mdutil -i off "$workDirectory" || die "mdutil failed, ABEND" 4
-
-pushd "$workDirectory" > /dev/null
-rm -rf .fseventsd .Spotlight-V* .Trashes ._.Trashes
-mkdir .fseventsd
-touch .fseventsd/no_log .metadata_never_index .Trashes
-popd > /dev/null
-
-printf "Spotlight disabled for $workDirectory\n\n"
+workDirectory=$(resolveFlySightMount)
+assertFlySightDirExists "$workDirectory"
+notifyUserWorkWith "$workDirectory"
+disableSpotlightIn "$workDirectory"
 
 exit 0
 
